import { WorkflowTemplate } from "@/types/workflow";

export const PRESET_TEMPLATES: WorkflowTemplate[] = [
  {
    id: "support-sales-router",
    name: "Customer Support vs Sales Router",
    category: "Customer Service",
    description: "Evaluates inbound customer inquiry text and routes between Support (Tier 2/Standard) and Sales (Enterprise/General).",
    nodes: [
      {
        id: "start_1",
        type: "start",
        position: { x: 250, y: 50 },
        data: { label: "Inbound Request Payload", description: "Raw user inquiry text input" },
      },
      {
        id: "node_support_check",
        type: "aiDecision",
        position: { x: 250, y: 180 },
        data: {
          label: "Is Technical Support?",
          prompt: "Is this message a technical support issue, bug report, or help request?",
          systemContext: "Analyze if the user needs technical assistance or account troubleshooting.",
          status: "idle",
        },
      },
      {
        id: "node_urgency_check",
        type: "aiDecision",
        position: { x: 50, y: 350 },
        data: {
          label: "Is High Priority Downtime?",
          prompt: "Does this mention critical system outage, urgent downtime, or broken production error?",
          systemContext: "Classify priority level of support issue.",
          status: "idle",
        },
      },
      {
        id: "node_sales_check",
        type: "aiDecision",
        position: { x: 460, y: 350 },
        data: {
          label: "Is Sales Inquiry?",
          prompt: "Is the user inquiring about buying, pricing plans, enterprise quotes, or scheduling a demo?",
          systemContext: "Identify commercial purchasing intent.",
          status: "idle",
        },
      },
      {
        id: "action_tier2",
        type: "action",
        position: { x: -60, y: 530 },
        data: {
          label: "Urgent PagerDuty Alert",
          actionType: "alert",
          actionDetails: "Escalated to On-Call Senior Support Engineers",
        },
      },
      {
        id: "action_support_queue",
        type: "action",
        position: { x: 180, y: 530 },
        data: {
          label: "Standard Support Queue",
          actionType: "ticket",
          actionDetails: "Created ZenDesk Ticket in Support Queue",
        },
      },
      {
        id: "action_sales_rep",
        type: "action",
        position: { x: 380, y: 530 },
        data: {
          label: "Route to Sales Rep",
          actionType: "crm",
          actionDetails: "Assigned lead to Enterprise Account Executive",
        },
      },
      {
        id: "action_kb_bot",
        type: "action",
        position: { x: 600, y: 530 },
        data: {
          label: "Auto KB Response",
          actionType: "bot",
          actionDetails: "Dispatched automated documentation articles",
        },
      },
    ],
    edges: [
      {
        id: "e_start_support",
        source: "start_1",
        target: "node_support_check",
        type: "decision",
      },
      {
        id: "e_supp_yes",
        source: "node_support_check",
        sourceHandle: "yes",
        target: "node_urgency_check",
        type: "decision",
        label: "YES",
        data: { decision: "YES" },
      },
      {
        id: "e_supp_no",
        source: "node_support_check",
        sourceHandle: "no",
        target: "node_sales_check",
        type: "decision",
        label: "NO",
        data: { decision: "NO" },
      },
      {
        id: "e_urg_yes",
        source: "node_urgency_check",
        sourceHandle: "yes",
        target: "action_tier2",
        type: "decision",
        label: "YES",
        data: { decision: "YES" },
      },
      {
        id: "e_urg_no",
        source: "node_urgency_check",
        sourceHandle: "no",
        target: "action_support_queue",
        type: "decision",
        label: "NO",
        data: { decision: "NO" },
      },
      {
        id: "e_sales_yes",
        source: "node_sales_check",
        sourceHandle: "yes",
        target: "action_sales_rep",
        type: "decision",
        label: "YES",
        data: { decision: "YES" },
      },
      {
        id: "e_sales_no",
        source: "node_sales_check",
        sourceHandle: "no",
        target: "action_kb_bot",
        type: "decision",
        label: "NO",
        data: { decision: "NO" },
      },
    ],
  },
  {
    id: "spam-moderation-flow",
    name: "Spam & Content Moderation",
    category: "Security",
    description: "Filters incoming text content through multi-stage safety and spam AI checks.",
    nodes: [
      {
        id: "start_spam",
        type: "start",
        position: { x: 250, y: 50 },
        data: { label: "User Submission Text", description: "Post or comment string" },
      },
      {
        id: "node_spam_check",
        type: "aiDecision",
        position: { x: 250, y: 180 },
        data: {
          label: "Is Spam or Phishing Link?",
          prompt: "Does this text contain spam links, crypto scams, or prize claims?",
          status: "idle",
        },
      },
      {
        id: "node_toxicity_check",
        type: "aiDecision",
        position: { x: 450, y: 340 },
        data: {
          label: "Contains Severe Toxic Language?",
          prompt: "Does this message contain hate speech, threats, or abusive language?",
          status: "idle",
        },
      },
      {
        id: "action_block",
        type: "action",
        position: { x: 100, y: 340 },
        data: { label: "Block & Ban Account", actionDetails: "Flagged user and deleted content" },
      },
      {
        id: "action_flag_review",
        type: "action",
        position: { x: 320, y: 500 },
        data: { label: "Quarantine Moderation Queue", actionDetails: "Submitted for human review" },
      },
      {
        id: "action_approve",
        type: "action",
        position: { x: 580, y: 500 },
        data: { label: "Approve & Publish", actionDetails: "Passed safety checks" },
      },
    ],
    edges: [
      { id: "e_sp_start", source: "start_spam", target: "node_spam_check", type: "decision" },
      { id: "e_sp_yes", source: "node_spam_check", sourceHandle: "yes", target: "action_block", type: "decision", label: "YES", data: { decision: "YES" } },
      { id: "e_sp_no", source: "node_spam_check", sourceHandle: "no", target: "node_toxicity_check", type: "decision", label: "NO", data: { decision: "NO" } },
      { id: "e_tox_yes", source: "node_toxicity_check", sourceHandle: "yes", target: "action_flag_review", type: "decision", label: "YES", data: { decision: "YES" } },
      { id: "e_tox_no", source: "node_toxicity_check", sourceHandle: "no", target: "action_approve", type: "decision", label: "NO", data: { decision: "NO" } },
    ],
  },
  {
    id: "lead-qualification-flow",
    name: "Lead Qualification & Prioritization",
    category: "Sales Automation",
    description: "Scores lead responses and routes high-intent enterprise accounts to immediate booking.",
    nodes: [
      {
        id: "start_lead",
        type: "start",
        position: { x: 250, y: 50 },
        data: { label: "Lead Response Form", description: "Submitted contact inquiry" },
      },
      {
        id: "node_company_check",
        type: "aiDecision",
        position: { x: 250, y: 180 },
        data: {
          label: "Is Enterprise / High Budget?",
          prompt: "Does the lead represent a company with large team size or high budget?",
          status: "idle",
        },
      },
      {
        id: "action_vip_sales",
        type: "action",
        position: { x: 100, y: 350 },
        data: { label: "Book Instant VIP Call", actionDetails: "Calendly VIP Link sent" },
      },
      {
        id: "action_nurture",
        type: "action",
        position: { x: 400, y: 350 },
        data: { label: "Add to Email Nurture", actionDetails: "Enrolled in 5-day email campaign" },
      },
    ],
    edges: [
      { id: "e_ld_start", source: "start_lead", target: "node_company_check", type: "decision" },
      { id: "e_comp_yes", source: "node_company_check", sourceHandle: "yes", target: "action_vip_sales", type: "decision", label: "YES", data: { decision: "YES" } },
      { id: "e_comp_no", source: "node_company_check", sourceHandle: "no", target: "action_nurture", type: "decision", label: "NO", data: { decision: "NO" } },
    ],
  },
];
